server:
  port: 8083

spring:
  application:
    name: eureka-server


# 配置 eureka
eureka:
  instance:
    hostname: localhost # 主机名，不配置时根据操作系统的主机名获取
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    register-with-eureka: true #是否讲自己注册到注册中心，默认false
    fetch-registry: true # 是否从注册中心获取注册信息，默认true
    registry-fetch-interval-seconds: 3
    service-url:  # eureka注册中心的地址信息
      defaultZone: http://localhost:8083/eureka/





