server:
  port: 8031

spring:
  application:
    name: service-product


# 配置 eureka
eureka:
  client:
    register-with-eureka: true #是否讲自己注册到注册中心，默认false
    fetch-registry: true
    service-url:  # eureka注册中心的地址信息
      defaultZone: http://localhost:8083/eureka/





